(define (problem tufox-instance)
  (:domain tufox)
  (:objects
    detective player bunny1 bunny2 bunny3 bunny4 - agent
    tower    library    armory    observatory    hall    dining_room    kitchen    storage    study    throne_room    bathroom    bedroom    chapel    dungeon    wine_cellar    balcony - room
  )
  (:init
    (alive detective)
    (is-detective detective)
    (alive player)
    (at player study)
    (not-inspected player)
    (alive bunny1)
    (at bunny1 library)
    (not-inspected bunny1)
    (alive bunny2)
    (at bunny2 storage)
    (not-inspected bunny2)
    (alive bunny3)
    (at bunny3 study)
    (not-inspected bunny3)
    (alive bunny4)
    (at bunny4 balcony)
    (not-inspected bunny4)
    (at detective storage)
    (connected tower hall)
    (connected tower library)
    (connected library dining_room)
    (connected library tower)
    (connected library armory)
    (connected armory kitchen)
    (connected armory library)
    (connected armory observatory)
    (connected observatory storage)
    (connected observatory armory)
    (connected hall tower)
    (connected hall study)
    (connected hall dining_room)
    (connected dining_room library)
    (connected dining_room throne_room)
    (connected dining_room hall)
    (connected dining_room kitchen)
    (connected kitchen armory)
    (connected kitchen bathroom)
    (connected kitchen dining_room)
    (connected kitchen storage)
    (connected storage observatory)
    (connected storage bedroom)
    (connected storage kitchen)
    (connected study hall)
    (connected study chapel)
    (connected study throne_room)
    (connected throne_room dining_room)
    (connected throne_room dungeon)
    (connected throne_room study)
    (connected throne_room bathroom)
    (connected bathroom kitchen)
    (connected bathroom wine_cellar)
    (connected bathroom throne_room)
    (connected bathroom bedroom)
    (connected bedroom storage)
    (connected bedroom balcony)
    (connected bedroom bathroom)
    (connected chapel study)
    (connected chapel dungeon)
    (connected dungeon throne_room)
    (connected dungeon chapel)
    (connected dungeon wine_cellar)
    (connected wine_cellar bathroom)
    (connected wine_cellar dungeon)
    (connected wine_cellar balcony)
    (connected balcony bedroom)
    (connected balcony wine_cellar)
  )
  (:goal (inspected bunny2))
)
